# Generated by Django 5.1.6 on 2026-05-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_zh", models.CharField(max_length=64)),
                ("name_en", models.CharField(max_length=64)),
                ("color_hex", models.CharField(default="#3B82F6", max_length=7)),
                ("icon", models.CharField(default="tag", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, unique=True)),
                ("language", models.CharField(default="en", max_length=8)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("blocked", "Blocked"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trends.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "window",
                    models.CharField(
                        choices=[("24h", "24h"), ("7d", "7d"), ("30d", "30d")],
                        default="30d",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("caption", models.CharField(max_length=180)),
                ("template", models.CharField(default="A", max_length=16)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("blocked", "Blocked"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_titles",
                        to="trends.phrase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="trends.phrase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TikTokRawSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("tiktok", "TikTok")], default="tiktok", max_length=16
                    ),
                ),
                ("region", models.CharField(default="US", max_length=8)),
                ("source_url", models.URLField()),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("title_text", models.TextField(blank=True, default="")),
                ("caption_text", models.TextField(blank=True, default="")),
                ("raw_metrics", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["platform", "region", "fetched_at"],
                        name="trends_tikt_platfor_441f2a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhraseMetricWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "window",
                    models.CharField(
                        choices=[("24h", "24h"), ("7d", "7d"), ("30d", "30d")],
                        max_length=8,
                    ),
                ),
                ("heat_score", models.IntegerField()),
                ("growth_prev_window", models.FloatField(blank=True, null=True)),
                ("growth_vs_7d_avg", models.FloatField(blank=True, null=True)),
                ("score_explain", models.TextField(blank=True, default="")),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="trends.phrase",
                    ),
                ),
            ],
            options={"unique_together": {("phrase", "window")},},
        ),
    ]
