# Generated by Django 5.2.5 on 2026-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "类别", "verbose_name_plural": "类别管理"},
        ),
        migrations.AlterModelOptions(
            name="evidencelink",
            options={"verbose_name": "证据链接", "verbose_name_plural": "证据链接"},
        ),
        migrations.AlterModelOptions(
            name="generatedtitle",
            options={"verbose_name": "生成标题", "verbose_name_plural": "生成标题"},
        ),
        migrations.AlterModelOptions(
            name="phrase",
            options={"verbose_name": "爆款词短语", "verbose_name_plural": "爆款词短语"},
        ),
        migrations.AlterModelOptions(
            name="phrasemetricwindow",
            options={"verbose_name": "短语窗口指标", "verbose_name_plural": "短语窗口指标"},
        ),
        migrations.AlterModelOptions(
            name="ruleconfig",
            options={"verbose_name": "规则配置", "verbose_name_plural": "规则配置"},
        ),
        migrations.AlterModelOptions(
            name="tiktokrawsnapshot",
            options={"verbose_name": "TikTok原始快照", "verbose_name_plural": "TikTok原始快照"},
        ),
        migrations.AddField(
            model_name="generatedtitle",
            name="ai_reply",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="generatedtitle",
            name="feedback_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="generatedtitle",
            name="refined_count",
            field=models.IntegerField(default=0),
        ),
    ]
