# Generated by Django 5.2.5 on 2026-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0002_alter_category_options_alter_evidencelink_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tiktokrawsnapshot",
            options={"verbose_name": "平台原始快照", "verbose_name_plural": "平台原始快照"},
        ),
        migrations.AlterField(
            model_name="tiktokrawsnapshot",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("gtrends", "Google Trends"),
                    ("atp", "AnswerThePublic"),
                ],
                default="tiktok",
                max_length=16,
            ),
        ),
    ]
