# Generated by Django 5.2.5 on 2026-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0003_alter_tiktokrawsnapshot_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("tiktok", "TikTok"),
                            ("gtrends", "Google Trends"),
                            ("atp", "AnswerThePublic"),
                        ],
                        default="tiktok",
                        max_length=16,
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.BooleanField(default=False)),
                ("last_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "数据源状态", "verbose_name_plural": "数据源状态"},
        ),
    ]
