# Generated by Django 5.2.5 on 2026-05-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0004_datasourcestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourcestatus",
            name="consecutive_failures",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="datasourcestatus",
            name="first_failure_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
