# Generated by Django 5.2.5 on 2026-05-21 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0005_datasourcestatus_consecutive_failures_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="phrase",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phrase",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_phrases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="deleted_reason_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="phrase",
            name="deleted_reason_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invalid", "无效字段"),
                    ("illegal", "非法字段"),
                    ("duplicate", "重复字段"),
                    ("custom", "自定义理由"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PhraseDeleteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("invalid", "无效字段"),
                            ("illegal", "非法字段"),
                            ("duplicate", "重复字段"),
                            ("custom", "自定义理由"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phrase_delete_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delete_logs",
                        to="trends.phrase",
                    ),
                ),
            ],
            options={"verbose_name": "关键词删除记录", "verbose_name_plural": "关键词删除记录"},
        ),
    ]
