# Generated by Django 5.2.5 on 2026-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0006_phrase_deleted_at_phrase_deleted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyFetchCheckpoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", max_length=32, unique=True)),
                ("last_success_date", models.DateField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "每日抓取检查点", "verbose_name_plural": "每日抓取检查点"},
        ),
    ]
