# Generated by Django 5.2.5 on 2026-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0007_dailyfetchcheckpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyfetchcheckpoint",
            name="key",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="datasourcestatus",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("gtrends", "Google Trends"),
                    ("atp", "AnswerThePublic"),
                ],
                default="tiktok",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tiktokrawsnapshot",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("gtrends", "Google Trends"),
                    ("atp", "AnswerThePublic"),
                ],
                default="tiktok",
                max_length=16,
            ),
        ),
    ]
