# Generated by Django 5.2.5 on 2026-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0008_alter_dailyfetchcheckpoint_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrase",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("gtrends", "Google Trends"),
                    ("atp", "AnswerThePublic"),
                ],
                default="tiktok",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="phrase", name="text", field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="phrase", unique_together={("text", "platform")},
        ),
    ]
