# Generated by Django 5.2.5 on 2026-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0010_dailyworkflowrun_assistantmessagelog"),
    ]

    operations = [
        migrations.AlterModelOptions(name="category", options={},),
        migrations.AlterModelOptions(name="dailyfetchcheckpoint", options={},),
        migrations.AlterModelOptions(name="datasourcestatus", options={},),
        migrations.AlterModelOptions(name="evidencelink", options={},),
        migrations.AlterModelOptions(name="generatedtitle", options={},),
        migrations.AlterModelOptions(name="phrase", options={},),
        migrations.AlterModelOptions(name="phrasedeletelog", options={},),
        migrations.AlterModelOptions(name="phrasemetricwindow", options={},),
        migrations.AlterModelOptions(name="ruleconfig", options={},),
        migrations.AlterModelOptions(name="tiktokrawsnapshot", options={},),
        migrations.AlterField(
            model_name="datasourcestatus",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("youtube", "YouTube"),
                    ("gtrends", "Google Trends"),
                    ("atp", "AnswerThePublic"),
                ],
                default="tiktok",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="deleted_reason_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invalid", "Invalid field"),
                    ("illegal", "Illegal field"),
                    ("duplicate", "Duplicate field"),
                    ("custom", "Custom reason"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("youtube", "YouTube"),
                    ("gtrends", "Google Trends"),
                    ("atp", "AnswerThePublic"),
                ],
                default="tiktok",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="phrasedeletelog",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("invalid", "Invalid field"),
                    ("illegal", "Illegal field"),
                    ("duplicate", "Duplicate field"),
                    ("custom", "Custom reason"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tiktokrawsnapshot",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("youtube", "YouTube"),
                    ("gtrends", "Google Trends"),
                    ("atp", "AnswerThePublic"),
                ],
                default="tiktok",
                max_length=16,
            ),
        ),
    ]
