# Generated by Django 5.2.5 on 2026-05-22 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0011_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalHumanSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("gtrends", "Google Trends"),
                            ("atp", "AnswerThePublic"),
                        ],
                        default="tiktok",
                        max_length=16,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("trend_analysis", "Trend Analysis"),
                            ("platform_compare", "Platform Compare"),
                            ("title_refine", "Title Refine"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(default="fallback", max_length=32)),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("trace_id", models.CharField(db_index=True, max_length=64)),
                (
                    "livetalking_status",
                    models.CharField(default="skipped", max_length=16),
                ),
                ("livetalking_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="digital_human_session_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="digital_human_logs",
                        to="trends.phrase",
                    ),
                ),
            ],
        ),
    ]
