# Generated by Django 5.2.5 on 2026-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0012_digitalhumansessionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedtitle",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("blocked", "Blocked"),
                    ("pending_review", "Pending Review"),
                ],
                default="low",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("blocked", "Blocked"),
                    ("pending_review", "Pending Review"),
                ],
                default="low",
                max_length=16,
            ),
        ),
    ]
